/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import Controller.ProviderMenu;
import Model.FirebaseConnect;
import com.google.api.core.ApiFuture;
import com.google.cloud.firestore.DocumentReference;
import com.google.cloud.firestore.Precondition;
import com.google.cloud.firestore.WriteResult;
import com.google.firebase.cloud.FirestoreClient;
import java.io.IOException;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author ESTUDIANTES
 */
public class InterfazSeleccionarMenu extends javax.swing.JFrame {

    /**
     * Creates new form InterfazSeleccionarMenu
     */
    public InterfazSeleccionarMenu() throws IOException {
        FirebaseConnect.conectarFirebase();
        
        initComponents();
        this.setLocationRelativeTo(null);
        ProviderMenu.cargarTabla(Tabla);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BtGuardar = new javax.swing.JButton();
        tfNombre = new javax.swing.JTextField();
        tfMesa = new javax.swing.JTextField();
        tfId = new javax.swing.JTextField();
        menus = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        BtBorrar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BtGuardar.setText("Realizar pedido");
        BtGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtGuardarActionPerformed(evt);
            }
        });

        tfNombre.setBorder(null);

        tfMesa.setBorder(null);

        tfId.setBackground(new java.awt.Color(242, 242, 242));
        tfId.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tfId.setEnabled(false);

        menus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccionar menu", "Hamburguesa", "Papas", "Vegetales", "Carne", "Galletas", "Agua", "Soda", "Frijoles", "Lentejas", "Yuca", "Arroz", "Arepa", "Huevo", "Leche", "Queso", "Pan", "Yogurt", "Kumis", "Tamal", "Pollo" }));
        menus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menusActionPerformed(evt);
            }
        });

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        Tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Tabla);

        BtBorrar.setText("Borrar orden");

        jLabel1.setText("Nombre:");

        jLabel2.setText("Numero de mesa");

        jLabel3.setText("Numero de orden:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtGuardar)
                        .addGap(28, 28, 28)
                        .addComponent(BtBorrar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(tfNombre)
                        .addComponent(tfMesa)
                        .addComponent(tfId)
                        .addComponent(menus, 0, 240, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 171, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(115, 115, 115))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tfMesa, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(jLabel2)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tfId, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(jLabel3)))
                        .addGap(29, 29, 29)
                        .addComponent(menus, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtGuardar)
                            .addComponent(BtBorrar))))
                .addContainerGap(276, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_menusActionPerformed

    private void BtGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtGuardarActionPerformed
        guardarMenu();
    }//GEN-LAST:event_BtGuardarActionPerformed

    private void TablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaMouseClicked
        int seleccion = Tabla.getSelectedRow();
       tfId.setText(Tabla.getValueAt(seleccion, 0)+"");
       tfNombre.setText(Tabla.getValueAt(seleccion, 1)+"");
       tfMesa.setText(Tabla.getValueAt(seleccion, 2)+"");
       String comidaselecc = (String) Tabla.getValueAt(seleccion, 3);
       int indexs = 0;
       
       if(comidaselecc.equals("Hamburguesa")){
           indexs = 1;
       } else if(comidaselecc.equals("Papas")){
           indexs = 2;
       } else if(comidaselecc.equals("Vegetales")){
           indexs = 3;
       } else if(comidaselecc.equals("Carne")){
           indexs = 4;
       }else if(comidaselecc.equals("Galletas")){
           indexs = 5;
       }else if(comidaselecc.equals("Agua")){
           indexs = 6;
       }else if(comidaselecc.equals("Soda")){
           indexs = 7;
       }else if(comidaselecc.equals("Frijoles")){
           indexs = 8;
       }else if(comidaselecc.equals("Lentejas")){
           indexs = 9;
       }else if(comidaselecc.equals("Yuca")){
           indexs = 10;
       }else if(comidaselecc.equals("Arroz")){
           indexs = 11;
       }else if(comidaselecc.equals("Arepa")){
           indexs = 12;
       }else if(comidaselecc.equals("Huevo")){
           indexs = 13;
       }else if(comidaselecc.equals("Leche")){
           indexs = 14;
       }else if(comidaselecc.equals("Queso")){
           indexs = 15;
       }else if(comidaselecc.equals("Pan")){
           indexs = 16;
       }else if(comidaselecc.equals("Yogurt")){
           indexs = 17;
       }else if(comidaselecc.equals("Kumis")){
           indexs = 18;
       }else if(comidaselecc.equals("Tamal")){
           indexs = 19;
       }else if(comidaselecc.equals("Pollo")){
           indexs = 20;
       }
       menus.setSelectedIndex(indexs);
    }//GEN-LAST:event_TablaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazSeleccionarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazSeleccionarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazSeleccionarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazSeleccionarMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new InterfazSeleccionarMenu().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(InterfazSeleccionarMenu.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtBorrar;
    private javax.swing.JButton BtGuardar;
    private javax.swing.JTable Tabla;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> menus;
    private javax.swing.JTextField tfId;
    private javax.swing.JTextField tfMesa;
    private javax.swing.JTextField tfNombre;
    // End of variables declaration//GEN-END:variables

    private void guardarMenu() {
        int id = (int)(Math.random() * 100000);
        int index = menus.getSelectedIndex();
        String comidaselec = null;

        if (index == 1){
            comidaselec = "Hamburguesa"; 
        } else if(index == 2){
            comidaselec = "Papas";
        } else if(index == 3){
            comidaselec = "Vegetales";
        } else if(index == 4){
            comidaselec = "Carne";
        }else if(index == 5){
            comidaselec = "Galletas";
        }else if(index == 6){
            comidaselec = "Agua";
        }else if(index == 7){
            comidaselec = "Soda";
        }else if(index == 8){
            comidaselec = "Frijoles";
        }else if(index == 9){
            comidaselec = "Lentejas";
        }else if(index == 10){
            comidaselec = "Yuca";
        }else if(index == 11){
            comidaselec = "Arroz";
        }else if(index == 12){
            comidaselec = "Arepa";
        }else if(index == 13){
            comidaselec = "Huevo";
        }else if(index == 14){
            comidaselec = "Leche";
        }else if(index == 15){
            comidaselec = "Queso";
        }else if(index == 16){
            comidaselec = "Pan";
        }else if(index == 17){
            comidaselec = "Yogurt";
        }else if(index == 18){
            comidaselec = "Kumis";
        }else if(index == 19){
            comidaselec = "Tamal";
        }else if(index == 20){
            comidaselec = "Pollo";
        } 
        
        try {
            Map<String, Object> datos = new HashMap<>();
            datos.put("Nombre", tfNombre.getText());
            datos.put("Mesa", tfMesa.getText());
            datos.put("Comida", comidaselec);
            ProviderMenu.guardarMenu("Pedido", String.valueOf(id), datos);
            JOptionPane.showMessageDialog(null, "Guardado con exito");
            clearEt();
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
            JOptionPane.showMessageDialog(null, "No se ha podido guardar el pedido" + e.getMessage());
        } finally{
            ProviderMenu.cargarTabla(Tabla);
        }
    }
    
    private void eliminar() {
        String idDoc = tfId.getText();
        try {
            ProviderMenu.EliminarPedido("Persona", idDoc);
            JOptionPane.showMessageDialog(null, "Eliminado con exito");
            clearEt();
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        } finally{
            ProviderMenu.cargarTabla(Tabla);
        }
    }
    
    
    private void clearEt() {
        tfId.setText("");
        tfMesa.setText("");
        tfNombre.setText("");
        menus.setSelectedItem(0);
    }
}
